### ISSUE TITLE
Recreating adjustments for RAW images

### ISSUE THREAD

**Issue by RhetTbull** [neilpa/photohack#2]
Currently, [osxphotos](https://github.com/RhetTbull/osxphotos) cannot [export](https://github.com/RhetTbull/osxphotos/issues/225) edited versions of RAW images because Photos stores no jpeg version of the adjustments -- it only stores the `.plist` with the adjustment data.  I wonder if there's enough info in the adjustment data returned by `photohack` to re-create the edited image (e.g. apply all the adjustments via CoreImage) to create a rendered jpeg?  Certainly beyond my skills at the moment but I'm willing to try to learn enough Swift to experiment with this.  Alternatively, `photohack` might be able to request the rendered edited photo via PhotoKit.

**Comment by neilpa** [comment]
Exporting the rendered edit via PhotoKit would be ideal. I'm pretty sure I saw an option for that as part of fetching asset image data but now I'm struggling to find it again in the PhotoKit docs.

If that doesn't work, it _should_ be possible to apply all the adjustments now that I've figured out the [schema](https://github.com/neilpa/photohack#adjustments-schema) and how to extract the associated dictionaries. There's _a lot_ of them though so it's going to be non-trivial to map them all onto onto CoreImage operations.

**Comment by neilpa** [comment]
Found the relevant PhotoKit docs. The [`requestImage*`](https://developer.apple.com/documentation/photokit/phimagemanager/1616964-requestimageforasset) methods of `PHImageManager` have an [`PHImageRequestOptions`](https://developer.apple.com/documentation/photokit/phimagerequestoptions) argument with a `version` property you can set to [`PHImageRequestOptionsVersion.current`](https://developer.apple.com/documentation/photokit/phimagerequestoptionsversion/current).

**Comment by neilpa** [comment]
See #3 for a quick hack at exporting adjusted JPEGs.

**Comment by neilpa** [comment]
Merged and tagged a [new release](https://github.com/neilpa/photohack/releases/tag/v0.0.4) with a pre-compiled binary. For now it's a simple export that dumps `<UUID>.jpg` files in the provided directory.

```
photohack path/to/some.photoslibrary jpegs path/to/export <UUID>...
```

Could make this more flexible for interaction with `osxphotos` if you want to go this route.
