### ISSUE TITLE
Any luck with NUAdjustmentSerialization?

### ISSUE THREAD

**Issue by RhetTbull** [neilpa/photohack#4]
>TODO: May be able to use NUAdjustmentSerialization directly to load an adjustment plist file from disk and bypass the permissions and other hacks for PhotoKit.

Did you ever have any success de-serializing the adjustment plist data?  

I've added some [PhotoKit methods](https://github.com/RhetTbull/osxphotos/blob/master/osxphotos/photokit.py) (assisted by the work you did with PhotoHack) to [osxphotos](https://github.com/RhetTbull/osxphotos/) but would really like to be able to get the orientation for adjusted photos without messing with PhotoKit.

If you have done any more experimenting with this and have any pointers on where to start, I'd be happy to continue hacking at this.

**Comment by neilpa** [comment]
I didn't spend much time experimenting with this, but I do have some pointers for you.

I _think_ [`[NUAdjustmentSerialization compositionFromPropertyList:error:]`](https://github.com/w0lfschild/macOS_headers/blob/d33c6f112848f4278ae6f953d11885937492895f/macOS/PrivateFrameworks/NeutrinoCore/21/NUAdjustmentSerialization.h#L13) is the method you want to use to get at the composition data. I suspect the first argument is either an `NSData` of the property list file contents OR the [deserialized data](https://developer.apple.com/documentation/foundation/nspropertylistserialization/1409678-propertylistwithdata). The second `error` arg may be useful in figuring this out.

In order to actually use those deserializing methods you'll probably need to copy/paste the `NUAdjustmentSerialization` header file and explicitly link NeutrinoCore to photohack. Also, I'd recommend sticking with Objective-C for this stuff. It's a lot easier to dynamically interrogate objects. The debugger can also basically be used like a REPL with the `po` command, e.g. `po [object method:arg]`.

If that works you should have an [`NUComposition`](https://github.com/w0lfschild/macOS_headers/blob/master/macOS/PrivateFrameworks/NeutrinoCore/21/NUComposition.h) object, probably the [`NUGenericComposition`](https://github.com/w0lfschild/macOS_headers/blob/master/macOS/PrivateFrameworks/NeutrinoCore/21/NUGenericComposition.h) subclass. The [`resolveSchema`](https://github.com/neilpa/photohack/blob/1283e3936f6a57db267a437ab744808a2c67d203/photohack/PhotoProxy.m#L121-L181) method can be used to extract the dictionary of a full schema dump. To get the actual settings you should be able to just use [this blob of code](https://github.com/neilpa/photohack/blob/1283e3936f6a57db267a437ab744808a2c67d203/photohack/PhotoProxy.m#L57-L65).

I also invited you to this repo so you can push branches directly here if you want. Let me know if that's useful or if you run into any issues or need more details.

**Comment by RhetTbull** [comment]
Thanks!  Appreciate the pointers. I'll play around with this and see what I can figure out. I've updated osxphotos to export face regions in XMP but getting the adjusted orientation directly from the plist would help this be more accurate.

**Comment by neilpa** [comment]
I spent a little time poking at this over the weekend without much success. I tried [`[NUAdjustmentSerialization compositionFromPropertyList:error:]`](https://github.com/w0lfschild/macOS_headers/blob/d33c6f112848f4278ae6f953d11885937492895f/macOS/PrivateFrameworks/NeutrinoCore/21/NUAdjustmentSerialization.h#L13) and some others I found in the NeutrinoCore headers. They all take an `NSDictionary`, however, using the dictionary from a deserialized adjustment `plist` file didn't work. I'll have to do some deeper digging to see if I can figure it out.

**Comment by neilpa** [comment]
After much spelunking in the private headers and trial/error I finally figured out how to decode adjustment plist data without using PhotoKit directly. The missing link is [`[PFAdjustmentSerialization deserializeDictionaryFromData:error:]`](https://github.com/w0lfschild/macOS_headers/blob/8979601bff0f290b553e2dc53c8663406dc247e5/macOS/PrivateFrameworks/PhotoLibraryServices/21/PFAdjustmentSerialization.h#L13) from the PhotoLibraryServices private framework.

This would still requiring bridging to ObjC from Python. However, you can give it the data directly from the plist and more importantly side-step prompting for permissions to access photos (tested to make sure this worked). Also, now that I know precisely what's encoded in the data blob I may have more success reverse engineering the format.

```objc
+ (NSDictionary*) decodeAdjustmentsFromPlist {
    NSString *dbPath = @"path/to/pics.photoslibrary";
    NSString *uuid = @"01234567-89AB-CDEF-FEDC-BA9876543210";
    NSString *plistPath = [NSString stringWithFormat:@"%@/resources/renders/%@/%@.plist", db, [uuid substringToIndex:1], uuid];

    NSError *err;
    NSData *plistData = [NSData dataWithContentsOfFile:plistPath options:0 error:&err];
    if (err != nil) {
        NSLog(@"Failed to read plist file: %@", err);
        return nil;
    }

    NSDictionary *plistDict = [NSPropertyListSerialization propertyListWithData:plistData options:0 format:nil error:&err];
    if (err != nil) {
        NSLog(@"Failed to get deserialize plist: %@", err);
        return nil;
    }
    
    Class serializer = NSClassFromString(@"PFAdjustmentSerialization");
    NSDictionary *adjustments = ((id (*)(id, SEL, id, id*))objc_msgSend)(serializer, @selector(deserializeDictionaryFromData:error:), plistDict[@"adjustmentData"], &err);
    if (err != nil) {
        NSLog(@"Failed to deserialize adjustment data: %@", err);
        return nil;
    }
    return adjustments;
}
```

```
(lldb) po adjustments
{
    adjustments =     (
                {
            enabled = 1;
            formatVersion = 1;
            identifier = RKRawDecodeOperation;
            settings =             {
                DGOperationClassName = DGRawDecodeOperation;
                DGOperationDisplayName = "RAW Fine Tuning";
                DGOperationIdentifier = RKRawDecodeOperation;
                enabled = 1;
                inputKeys =                 {
                    inputMethodVersion = 8;
                };
            };
        },
                {
            enabled = 1;
            formatVersion = 1;
            identifier = Crop;
            settings =             {
                constraintHeight = 0;
                constraintWidth = 0;
                height = 2972;
                straightenAngle = 0;
                width = 4457;
                xOrigin = 1041;
                yOrigin = 497;
            };
        }
    );
    formatVersion = 1;
    metadata =     {
        masterHeight = 4000;
        masterWidth = 6000;
        orientation = 1;
        pipelineVersion = "OSX.4";
    };
    versionInfo =     {
        appVersion = "161.0.120";
        buildNumber = 19G2021;
        platform = OSX;
        schemaRevision = 1;
    };
}
```

**Comment by neilpa** [comment]
Looks like [PhotoLibraryServices](https://github.com/w0lfschild/macOS_headers/tree/master/macOS/PrivateFrameworks/PhotoLibraryServices) is new in Catalina. There aren't any dumps for Big Sur in that directory but the [logs suggest](https://github.com/w0lfschild/macOS_headers/blob/master/logs/20E5172i_updates.log#L794) it still exists. I don't have easy access to a Big Sur machine to check if it works. Prior to that I'm guessing the same functionality is somewhere in [PhotoLibraryPrivate](https://github.com/w0lfschild/macOS_headers/tree/master/macOS/PrivateFrameworks/PhotoLibraryPrivate) framework.

**Comment by RhetTbull** [comment]
Woohoo!  I’m using Catalina day to day but do have a Big Sur partition for testing so I’ll give this a try.  I’ll need to figure out how to bridge the private framework from Python but this looks like it shouldn’t be too difficult to implement once I figure out the bridging bit.

**Comment by RhetTbull** [comment]
I've gotten your code translated to python and working.  Still need to test on Big Sur.

```python
import objc
from Foundation import NSClassFromString, NSData, NSPropertyListSerialization


# Load Photos framework needed to access PFAdjustmentSerialization class
objc.loadBundle(
    "PhotoLibraryServices",
    bundle_path="/System/Library/Frameworks/Photos.framework",
    module_globals=globals(),
)

objc.registerMetaDataForSelector(
    b"PFAdjustmentSerialization",
    b"deserializeDictionaryFromData:error:",
    {
        "retval": {"type": objc._C_ID},
        "arguments": {
            2: {"type": objc._C_ID},
            2 + 1: {"type": objc._C_PTR + objc._C_ID},
        },
    },
)

PFAdjustmentSerialization = NSClassFromString("PFAdjustmentSerialization")


def decode_adjustments_from_plist(plist_file):
    with objc.autorelease_pool():
        plist_data, err = NSData.dataWithContentsOfFile_options_error_(
            plist_file, 0, None
        )
        if err:
            print(f"error reading plist file {plist_file}: {err}")

        plist_dict = NSPropertyListSerialization.propertyListWithData_options_format_error_(
            plist_data, 0, None, None
        )

        return PFAdjustmentSerialization.deserializeDictionaryFromData_error_(
            plist_dict[0]["adjustmentData"], None
        )


if __name__ == "__main__":
    import sys

    for plist in sys.argv[1:]:
        print(plist)
        adjustments = decode_adjustments_from_plist(plist)
        print(adjustments)
```

```txt
python adjustments.py ~/Pictures/Test-10.15.7.photoslibrary/resources/renders/D/D05A5FE3-15FB-49A1-A15D-AB3DA6F8B068.plist
{
    adjustments =     (
                {
            enabled = 1;
            formatVersion = 1;
            identifier = RKRawDecodeOperation;
            settings =             {
                DGOperationClassName = DGRawDecodeOperation;
                DGOperationDisplayName = "RAW Fine Tuning";
                DGOperationIdentifier = RKRawDecodeOperation;
                enabled = 1;
                inputKeys =                 {
                    inputMethodVersion = 8;
                };
            };
        },
                {
            auto =             {
                auto =                 {
                    height = 4000;
                    straightenAngle = 0;
                    width = 6000;
                    xOrigin = 0;
                    yOrigin = 0;
                };
            };
            enabled = 1;
            formatVersion = 1;
            identifier = Crop;
            settings =             {
                constraintHeight = 0;
                constraintWidth = 0;
                height = 4000;
                straightenAngle = 0;
                width = 4634;
                xOrigin = 1366;
                yOrigin = 0;
            };
        }
    );
    formatVersion = 1;
    metadata =     {
        masterHeight = 4000;
        masterWidth = 6000;
        orientation = 8;
        pipelineVersion = "OSX.4";
    };
    versionInfo =     {
        appVersion = "161.0.120";
        buildNumber = 19H2;
        platform = OSX;
        schemaRevision = 1;
    };
}
```

**Comment by RhetTbull** [comment]
Tried this on Big Sur (11.0.1) and it works.  Interestingly, I noticed I loaded the Photos framework when I meant to load `/System/Library/PrivateFrameworks/PhotoLibraryServices.framework` and the code still worked. If I explicitly load PhotoLibraryServices.framework it also works.

**Comment by neilpa** [comment]
>  Interestingly, I noticed I loaded the Photos framework when I meant to load `/System/Library/PrivateFrameworks/PhotoLibraryServices.framework` and the code still worked. If I explicitly load PhotoLibraryServices.framework it also works.

The `PhotoLibraryServices.framework` is a dependency of top-level photos framework so it will get implicitly loaded. `otool -L path/to/some.framework` is a quick way to check.

```
$ otool -L /System/Library/Frameworks/Photos.framework/Photos
/System/Library/Frameworks/Photos.framework/Photos:
	/System/Library/Frameworks/Photos.framework/Versions/A/Photos (compatibility version 1.0.0, current version 161.0.120)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59306.140.4)
	/System/Library/PrivateFrameworks/MediaConversionService.framework/Versions/A/MediaConversionService (compatibility version 1.0.0, current version 161.0.120)
	/System/Library/Frameworks/ImageCaptureCore.framework/Versions/A/ImageCaptureCore (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1069.24.0)
	/System/Library/PrivateFrameworks/AppSupport.framework/Versions/A/AppSupport (compatibility version 1.0.0, current version 29.0.0)
	/System/Library/Frameworks/Metal.framework/Versions/A/Metal (compatibility version 1.0.0, current version 212.7.0)
	/System/Library/PrivateFrameworks/PhotosImagingFoundation.framework/Versions/A/PhotosImagingFoundation (compatibility version 1.0.0, current version 161.0.120)
	/System/Library/PrivateFrameworks/PhotoFoundation.framework/Versions/A/PhotoFoundation (compatibility version 1.0.0, current version 161.0.120)
	/System/Library/Frameworks/Contacts.framework/Versions/A/Contacts (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation (compatibility version 1.0.0, current version 2394.0.22)
	/System/Library/PrivateFrameworks/CloudPhotoServices.framework/Versions/A/CloudPhotoServices (compatibility version 1.0.0, current version 161.0.120)
	/System/Library/Frameworks/MediaToolbox.framework/Versions/A/MediaToolbox (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/PrivateFrameworks/PhotosFormats.framework/Versions/A/PhotosFormats (compatibility version 1.0.0, current version 161.0.120)
	/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/PrivateFrameworks/CloudPhotoLibrary.framework/Versions/A/CloudPhotoLibrary (compatibility version 1.0.0, current version 161.0.120)
	/System/Library/PrivateFrameworks/DCIMServices.framework/Versions/A/DCIMServices (compatibility version 1.0.0, current version 161.0.120)
	/System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation (compatibility version 1.0.0, current version 2.0.0)
	/System/Library/PrivateFrameworks/CoreMediaStream.framework/Versions/A/CoreMediaStream (compatibility version 1.0.0, current version 161.0.120)
	/System/Library/Frameworks/CoreData.framework/Versions/A/CoreData (compatibility version 1.0.0, current version 977.3.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1355.20.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1677.104.0)
	/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/Versions/A/PhotoLibraryServices (compatibility version 1.0.0, current version 161.0.120)
	/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/Versions/A/AssetsLibraryServices (compatibility version 1.0.0, current version 161.0.120)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
```

**Comment by neilpa** [comment]
I did more digging by looking at the implementation of  `[PFAdjustmentSerialization deserializeDictionaryFromData:error:]` in a disassembler. Turns out `adjustmentData` is a zlib compressed JSON blob using the `DEFLATE` strategy. Extracting in stock python 

```python
import plistlib, zlib
f = open('pics.photoslibrary/resources/renders/F/FFD18E55-BC97-4C6E-BF36-49E995FB2E2D.plist')
d = plistlib.readPlist(f)
print zlib.decompress(d['adjustmentData'].data, -zlib.MAX_WBITS)
```
```
'{"versionInfo":{"buildNumber":"19G2021","appVersion":"161.0.120","schemaRevision":1,"platform":"OSX"},"metadata":{"masterWidth":6000,"pipelineVersion":"OSX.4","masterHeight":4000,"orientation":1},"formatVersion":1,"adjustments":[{"formatVersion":1,"enabled":true,"settings":{"inputKeys":{"inputMethodVersion":"8"},"enabled":true,"DGOperationClassName":"DGRawDecodeOperation","DGOperationIdentifier":"RKRawDecodeOperation","DGOperationDisplayName":"RAW Fine Tuning"},"identifier":"RKRawDecodeOperation"},{"formatVersion":1,"enabled":true,"settings":{"height":2972,"straightenAngle":0,"constraintWidth":0,"width":4457,"xOrigin":1041,"yOrigin":497,"constraintHeight":0},"identifier":"Crop"}]}'
```

(I used python2 since I was having issues with `plistlib` in 3)

**Comment by RhetTbull** [comment]
Awesome detective work! I think a pure Python approach is preferable to using a private API but it also means it's subject to breakage if Apple ever changes the serialization algorithm. I'll play around with plistlib to see if I can get it working in Python3. I'm using it in osxphotos to deserialize the reverse geolocation data which is so tired in the database as an archived binary plist.

**Comment by RhetTbull** [comment]
Here's a working example in Python3 (needed to add "rb" to file open() to avoid the plistlib error).  Also shows how to grab the orientation (which is the thing I'm most interested in).  I'll add this to osxphotos and create a new PhotoInfo.adjustments property to return this data for edited photos. 

```
import plistlib
import zlib
import json

def decode_adjustments_from_plist(plist_file):
    with open(plist_file, "rb") as fd:
        plist_dict = plistlib.load(fd)
    return json.loads(zlib.decompress(plist_dict['adjustmentData'], -zlib.MAX_WBITS).decode())

if __name__ == "__main__":
    import sys

    for plist in sys.argv[1:]:
        print(plist)
        adjustments = decode_adjustments_from_plist(plist)
        print(adjustments)
        try:
            orientation = adjustments["metadata"]["orientation"]
        except KeyError:
            orientation = 0
        print(f"orientation = {orientation}")
```

**Comment by RhetTbull** [comment]
I've almost got this implemented in osxphotos.  One note: adjustments made by external editors or plug-ins cannot be read this way.  These still produce a plist file but the adjustmentData appears to be stored in whatever [format the editing application](https://developer.apple.com/documentation/photokit/phadjustmentdata) wants and produces errors if attempting to deserialize it, either with the zlib technique or using deserializeDictionaryFromData:error:.

From the Apple [docs](https://developer.apple.com/documentation/photokit/phadjustmentdata): 

>For each asset, Photos stores only one PHAdjustmentData object, representing the most recent edit made to the asset’s content.

Also, it seems that adjustments to movies cause deserialization errors so they must be stored in a different format.

**Comment by neilpa** [comment]
For the external case (and maybe the movie case) I'd assume the containing plist dictionary would have different values for `adjustmentEditorBundleID` and/or `adjustmentFormatIdentifier`. For an `osxphotos` API I wonder if it would be better to expose both the full plist contents and a best-effort way to decode the embedded data, falling back to the raw bytes otherwise.

**Comment by RhetTbull** [comment]
Good idea on providing the raw data — I’lll add an interface to do that.

> the containing plist dictionary would have different values for adjustmentEditorBundleID and/or adjustmentFormatIdentifier

That’s a good assumption but in my quick look, it seems this is not consistently handled — some apps do specify different values, some no value and some use Photos.

**Comment by RhetTbull** [comment]
I've added a [PhotoInfo.adjustments](https://github.com/RhetTbull/osxphotos#adjustments) property to osxphotos [v0.40.18](https://github.com/RhetTbull/osxphotos/releases/tag/v0.40.18) that provides an [AdjustmentsInfo](https://github.com/RhetTbull/osxphotos#adjustmentsinfo) object with properties to access the underlying plist fields, the raw adjustments data, and any decoded adjustments data.  Using this I was also able to fix PhotoInfo.orientation to return the correct orientation for edited photos.  Thanks again for your help with this!

**Comment by RhetTbull** [comment]
Some of the adjustmentData fields that fail to decode with zlib appear to be binary plists.  See notes [here](https://github.com/RhetTbull/osxphotos/issues/384).
